---
- name: Hello World Sample
  hosts: all
  gather_facts: no
  #vars:
  #  connectivity_test_destinations:
  #    - { ip: 192.168.50.2, port: 53, protocol: udp }
  vars_files:
     - test-vault-1.yml
  #roles:
  #  - ryandaniels.connectivity_test
  tasks:
    - name: Show facts
      debug:
        var: ansible_facts
    - name: Hello Message
      debug:
        #the facts are not complete with ansible automation platform runtime
        msg: "Hello World! - use fact cache: {{ ansible_facts['cmdline']['BOOT_IMAGE'] }} - {{ testpassword }}"
...
